version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: apt-get
          command: apt update && apt -y install build-essential gcc g++ cmake git wget libgoogle-glog-dev libboost-test-dev libboost-filesystem-dev libboost-serialization-dev libboost-system-dev pkg-config libeigen3-dev libclass-loader-dev libtinyxml-dev librosconsole-bridge-dev
      - checkout
      - run:
          name: chmod install script
          command: chmod +x install_dependencies.sh
      - run:
          name: run install script
          command: ./install_dependencies.sh
      - run:
          name: compile
          command: mkdir build && cd build && cmake -DROCK_TEST_ENABLED=ON -DWITH_PORTS=ON .. && make -j4 install

